---
output: pdf_document
---

```{r}
corridor_names_start = c("index", "step", "state")
corridor_names_end = c("action", "bias", "y", "estimate")
df = read.csv("test.csv")
names(df)[1:3] = corridor_names_start
names(df)[(length(df)-3):length(df)] = corridor_names_end

head(df)
```

```{r message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)

df2 = df %>% filter(state>10)

ggplot(data=df) + 
    geom_point(aes(x=state, y=estimate, color=index), alpha=0.7, position=position_dodge2(width = 0.5)) + 
    geom_point(aes(x=state, y=y), color="red", size=0.1, alpha=0.7, position=position_dodge2(width = 0.5)) + 
    scale_colour_continuous(type=2) + facet_grid(step~action)# + ylim(c(-2,2))
```

```{r message=FALSE, warning=FALSE}
max_index = dim(df)[1]
p = ggplot()

section = 100000
df$section = floor(df$index/section)
df$action = factor(df$action)

ggplot(data=df, aes(x=state, y=estimate, color=action)) +
    facet_wrap(~section) +
    geom_point() +
    geom_smooth(method="loess") +
    labs(title="Estimate")

ggplot(data=df, aes(x=state, y=y, color=action)) +
    facet_wrap(~section) +
    geom_point() +
    geom_smooth(method="loess") +
    labs(title="Target")

```
