---
output: pdf_document
---

```{r}
corridor_names = c("index", "state",  "bias", "action", "y")
deepsea_names = c("index", "state", "y_state", "times", "squarex", "squarey", "bias", "action", "y")
df = read.csv("test.csv")
names(df) = deepsea_names
head(df)
```

```{r}
library(ggplot2)
library(dplyr)

action_0_df = df %>% filter(action==0) 
action_1_df = df %>% filter(action==1)

ggplot(data=action_0_df) + 
    geom_point(aes(x=state, y=y, color=index), position=position_dodge2(width = 0.5)) + 
    scale_colour_continuous(type = 2)

ggplot(data=action_1_df) + 
    geom_point(aes(x=state, y=y, color=index), position=position_dodge2(width = 0.5)) + 
    scale_colour_continuous(type = 2)

```

```{r message=FALSE, warning=FALSE}
max_index = dim(df)[1]
p = ggplot()

section = 5000
action_1_df = action_1_df
action_1_df$section = floor(action_1_df$index/section)

action_0_df = action_0_df
action_0_df$section = floor(action_0_df$index/section)

ggplot(data=action_1_df, aes(x=state, y=y, color=index)) + 
    facet_wrap(~section) + 
    geom_point() + 
    geom_smooth(method="loess") + 
    scale_colour_continuous(type = 2) +
    labs(title="Action 1")

ggplot(data=action_0_df, aes(x=state, y=y, color=index)) + 
    facet_wrap(~section) + 
    geom_point() + 
    geom_smooth(method="loess") + 
    scale_colour_continuous(type = 2) +
    labs(title="Action 0")

```

## Train regression model

```{r}
model = lm(y ~ . , data=action_0_df)
action_0_df$model <- stats::predict(model, newdata=action_0_df)
ggplot(action_0_df) +
    geom_tile(aes(x=state, y=y_state, fill=model))

model = lm(y ~ . , data=action_1_df)
action_1_df$model <- stats::predict(model, newdata=action_1_df)
ggplot(action_1_df) +
    geom_tile(aes(x=state, y=y_state, fill=model))
```